### ISSUE TITLE
Empty lines are deleted under certain circumstances

### ISSUE THREAD

**Issue by DannyBen** [piotrmurach/tty-box#10]
### Describe the problem
When using text with empty lines, in some cases the empty lines are removed.
I observed this when trying to show the contents of a file inside a TTY::Box.

### Steps to reproduce the problem

```ruby
require 'tty-box'

def draw(text)
  options = { width: 30, height: 10 }
  puts TTY::Box.frame(options) { text }
end

system 'clear'
arr = ["hello\n", "\n", "world\n", "\n"]

draw (arr * 9).join
draw (arr * 2).join
```

### Actual behaviour

```
┌────────────────────────────┐
│hello                       │
│world                       │
│hello                       │
│world                       │
│hello                       │
│world                       │
│hello                       │
│world                       │
└────────────────────────────┘
┌────────────────────────────┐
│hello                       │
│                            │
│world                       │
│                            │
│hello                       │
│                            │
│world                       │
│                            │
└────────────────────────────┘
```

### Expected behaviour
Expected both outputs to be like the second one

### Describe your environment

* OS version: Ubuntu 18.04.3
* Ruby version: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
* TTY::Box version: tty-box (0.5.0)

**Comment by vlad-pisanov** [comment]
I have a similar issue: when there's multiple newlines between strings, they get removed, and instead appended at the end of the box:

`print TTY::Box.frame "dog\n\n\ncat"`

output:

```
┌───┐
│dog│
│cat│
│   │
│   │
└───┘
```

expected:

```
┌───┐
│dog│
│   │
│   │
│   │
|cat|
└───┘
```

**Comment by DannyBen** [comment]
@vlad-pisanov - yes, I also saw that behavior in some cases.
