### ISSUE TITLE
tty-box and tty-prompt will not work together

### ISSUE THREAD

**Issue by Jese310S** [piotrmurach/tty-box#11]
I am trying to use tty-box but my app already uses tty-prompt.  The are both requiring tty-cursor but require different versions.  Is it possible to use both box and prompt?

### environment

* Ruby version:2.7.0
* TTY::Box version:0.5

**Comment by piotrmurach** [comment]
Hi,

Thanks for using `tty-box` and `tty-prompt`.  Not sure what version of `tty-prompt` you're on but the latest for sure works fine. They both use `tty-cursor` version `0.7` under covers. So try upgrading `tty-prompt` first.
