### ISSUE TITLE
TTY::Box.frame fails if the text includes Pastel styled strings

### ISSUE THREAD

**Issue by artur-martsinkovskyi** [piotrmurach/tty-box#5]
### Describe the problem
When using TTY::Box with Pastel colored string an exception is raised. It seems like the frame algorithm is treating strings like \e[32mADS\e[0m improperly.

### Steps to reproduce the problem
```ruby
TTY::Box.frame { Pastel.new.green("ADS") }
```

### Actual behaviour
```
ArgumentError: negative argument
from /Users/user/.rvm/gems/ruby-2.3.3/gems/tty-box-0.3.0/lib/tty/box.rb:112:in `*'
```
### Expected behaviour
Writing a colored text in the box.
### Describe your environment

* OS version: Ubuntu 18.04.1
* Ruby version: 2.5.1
* TTY::Box version: 0.3.0

**Comment by piotrmurach** [comment]
Fixed and released as `v0.4.0`
