### ISSUE TITLE
Block content not rendering

### ISSUE THREAD

**Issue by BillyRuffian** [piotrmurach/tty-box#8]
Version 0.5.0, ruby 2.6.3p62, Mac, iTerm

```
1] pry(main)> print TTY::Box.frame "Hello world!"
┌────────────┐
│Hello world!│
└────────────┘
=> nil
[2] pry(main)> print TTY::Box.frame do
[2] pry(main)*   "Hello world!"
[2] pry(main)* end
┌─┐
└─┘
=> nil
```

**Comment by piotrmurach** [comment]
Hi Nigel,

Unfortunately, I don't think this is an issue with the gem. There is something weird going on with blocks and print call in Ruby. If you change your example from multiline block syntax to, single line, then it will work fine.

```ruby
print TTY::Box.frame { "Hello World!" }
┌────────────┐
│Hello World!│
└────────────┘
=> nil
```

So you need to be mindful of this, as you have already realised in your second comment. Ruby is weird and wonderful like this. 😉

**Comment by BillyRuffian** [comment]
That is super weird. Perhaps you could update your example in the readme?
