### ISSUE TITLE
Suggestion: Terminal UI

### ISSUE THREAD

**Issue by DannyBen** [piotrmurach/tty-box#9]
What are the chances of having the ability to create terminal UIs in TTY::Box (or somewhere else in the TTY toolkit)?

I think with what TTY brings to the table, having a minimum viable solution - one that allows creating panels that can a) be refreshed on interval and b) always contain their own content - is not too far out of reach, is it?

So we can do UIs like this, without relying on the complex ncurses related projects?

![image](https://user-images.githubusercontent.com/2405099/67417164-ce9e6300-f5d0-11e9-83e9-0e3e6714cfff.png)

Ideally (but I know highly unlikely), I wish Ruby would have something similar to Go's [termui][1]:

![image](https://user-images.githubusercontent.com/2405099/67417264-086f6980-f5d1-11e9-8301-c1e7372df918.png)

[1]: https://github.com/gizak/termui

**Comment by piotrmurach** [comment]
I really like your suggestion and think that's the ultimate future for TTY. Provide the ability to build rich terminal interfaces. However, before this dream is realised many things have to happen. 

The most important of them is to make components work with absolutely positioned content like [tty-pie](https://github.com/piotrmurach/tty-pie#25-position). Components like `tty-progressbar`, `tty-spinner` or `tty-tree` could be made to work this way or alternatively they could inherit parent box size to determine their own display width etc...

The second thing that needs to happen. There are still a few components missing like plot lines or sparklines to help with graphical interfaces. I think adding more components would get TTY much closer to rich UIs.

As for `tty-box`, for me, its sole purpose is drawing terminal boxes. I wouldn't want to expand it to start handling complex terminal layouts/dashboards. I feel this belongs into another gem such as `tty-ui` which would further build on the concept with an easy and declarative way to build layouts out of boxes. This could mimic the concept of CCS grids where user would specify how many panels they want and assign proportional values to each of them. They could also specify the type of a box, for example, a progress bar box would have already preconfigured formatting and display. But this requires some thought as to how it would work. I may create a repository so we can collect thoughts/ideas.

As for working on the idea. Finding time for OSS is a constant challenge. I have already many plans for things I'm going to do in the next few months. One of them is rewritting `tty` gem to remove direct dependency on bundler.

**Comment by DannyBen** [comment]
Sounds great. I agree it is a separate gem, only TTY Box was the place that made most sense to post an issue :).

**Comment by kevinelliott** [comment]
Any progress on this thinking? Would love to be able to have CLI dashboards like this. And also, the ability to have auto-scrolling content inside of a box (following content output).

**Comment by piotrmurach** [comment]
@kevinelliott Thank you for expressing support for this. I'm all for the idea and have plans for many new components that will make this possible. However, as you probably imagine to get to such a place requires plenty of work in my limited spare time. I maintain many Ruby projects including 25 TTY gems. My priorities currently include updating strings components like [strings-case](https://github.com/piotrmurach/strings-case) and making a new release of [tty toolkit](https://github.com/piotrmurach/tty). I enabled [discussions](https://github.com/piotrmurach/tty/discussions/categories/ideas) in the TTY project where you can share your ideas for new components. I had been thinking about the viewport scrolling component but it will need to wait for some unspecified time before I get around to implementing it. I wish I had a better answer but that's how things are at the moment.
